version: "3"

services:
  midra-lab-zenn:
    container_name: midra-lab-zenn
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_NAME: midra-lab
        GROUP_NAME: midra-lab
        USER_UID: 1000
        USER_GID: 1000
    ports:
      - "8000:8000"
    volumes:
      - .:/home/midra-lab/contents:cached
    command: npx zenn preview